config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'residential#index'
  get 'residential/data', :defaults => { format: 'json'}

  get 'bar-chart' => 'residential#bar_chart'
  get 'residential/bar_data', :defaults => { format: 'json'}

  get 'scatter-plot' => 'residential#scatter_plot'
  get 'box-plot' => 'residential#box_plot'
  get 'residential/scatter_data', :defaults => { format: 'json'}



  root 'residential#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sales_figure.rb
class SalesFigure < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/residential_controller.rb
class ResidentialController < ApplicationController
  def index; end

  def data
    totals = SalesFigure.group(:jurisdiction).sum(:total_sales)
    render :json => { totals: totals }
  end

  def bar_chart; end

  def bar_data
    bar_data = SalesFigure.
    select(:id, :zipcode, :median_value).
      where(:jurisdiction => 'Baltimore').
      order('median_value DESC, zipcode')
    render :json => { bar_data: bar_data }
  end

  def scatter_plot; end
  def box_plot; end

  def scatter_data
    data = SalesFigure.
      select(:id, :zipcode, :jurisdiction, :median_value, :total_sales).
      order(:jurisdiction)
    render :json => {scatter_data: data}
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/residential_helper.rb
module ResidentialHelper
end

app/views/layouts/_footer.html.erb
<div class='footer'>
  <%= link_to 'Pie Chart ', index_path%>|<%= link_to ' Bar Chart', bar_chart_path%>|
  <%= link_to ' Scatter Plot ', scatter_plot_path %>|<%= link_to ' Box Plot ', box_plot_path%>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sales</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js' %>
    <%#= javascript_include_tag "https://api.tiles.mapbox.com/mapbox.js/v2.2.4/mapbox.js" %>
    <%#= stylesheet_link_tag "https://api.tiles.mapbox.com/mapbox.js/v2.2.4/mapbox.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/residential/bar_chart.html.erb
<!-- A barchart will magically appear here -->
<div id="chart"></div>

<script>
$(document).on('ready page:load', function(event) {
  // apply non-idempotent transformations to the body
  makeBar();
});
</script>

app/views/residential/box_plot.html.erb
<h2>Box Plot</h2>
    <script src="https://d3js.org/d3.v4.min.js"></script>
<!-- A scatter plot will magically appear here -->

<div id="plot"></div>

<script>
$(document).on('ready page:load', function(event) {
  // apply non-idempotent transformations to the body
  makeBoxPlot();
});
</script>

app/views/residential/index.html.erb
<!-- A pie chart will magically appear here -->
<script>
$(document).on('ready page:load', function(event) {
  // apply non-idempotent transformations to the body
  makePie();
});
</script>

app/views/residential/scatter_plot.html.erb
<!-- A scatter plot will magically appear here -->

<div id="plot"></div>

<script>
$(document).on('ready page:load', function(event) {
  // apply non-idempotent transformations to the body
  makeScatter();
});
</script>